# Form implementation generated from reading ui file 'load_label_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 210)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.select_dir_button = QtWidgets.QPushButton(Dialog)
        self.select_dir_button.setGeometry(QtCore.QRect(130, 110, 113, 32))
        self.select_dir_button.setObjectName("select_dir_button")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 60, 311, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.single_phase_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.single_phase_radio_button.setObjectName("single_phase_radio_button")
        self.horizontalLayout_2.addWidget(self.single_phase_radio_button)
        self.multiple_phase_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.multiple_phase_radio_button.setObjectName("multiple_phase_radio_button")
        self.horizontalLayout_2.addWidget(self.multiple_phase_radio_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 311, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dicom_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.dicom_radio_button.setObjectName("dicom_radio_button")
        self.horizontalLayout.addWidget(self.dicom_radio_button)
        self.nifti_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.nifti_radio_button.setObjectName("nifti_radio_button")
        self.horizontalLayout.addWidget(self.nifti_radio_button)
        self.tiff_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tiff_radio_button.setObjectName("tiff_radio_button")
        self.horizontalLayout.addWidget(self.tiff_radio_button)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.select_dir_button.setText(_translate("Dialog", "Select file/folder"))
        self.single_phase_radio_button.setText(_translate("Dialog", "Single Phase"))
        self.multiple_phase_radio_button.setText(_translate("Dialog", "Multiple Phases"))
        self.dicom_radio_button.setText(_translate("Dialog", "Dicom"))
        self.nifti_radio_button.setText(_translate("Dialog", "Nifti"))
        self.tiff_radio_button.setText(_translate("Dialog", "Tiff"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
